name: Valet Plus test pipeline

on:
  push:
    branches: [ 2.x ]
  pull_request:
    branches: [ 2.x ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel# All actions starting with [INSTALL] are installation instructions that can be found
# in the Valet+ installation wiki page: https://github.com/weprovide/valet-plus/wiki/Installation
jobs:
  test:
    # Build on Catalina and later Big Sur (Not public released yet: https://github.com/actions/virtual-environments/issues/2486)
    runs-on: [macos-10.15]

    # A workflow run is made up of one or more jobs that can run sequentially or in parallel# All actions starting with [INSTALL] are installation instructions that can be found
    # in the Valet+ installation wiki page: https://github.com/weprovide/valet-plus/wiki/Installation
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Valet install command test cases
      - name: '[INSTALL] Brew update'
        run: brew update
